import { Link, useRouter } from 'expo-router';
import { ScrollView, Text, View } from 'react-native';
import { Card, Eyebrow, IconButton, Button } from '../../components/ui';
import { deadlines, notes } from '../../data/demo';
import { useTheme } from '../../hooks/use-theme';

export default function Home() {
  const { colors, dark, toggle } = useTheme(); const router = useRouter();
  return <ScrollView contentInsetAdjustmentBehavior="automatic" style={{ backgroundColor: colors.bg }} contentContainerStyle={{ padding: 20, paddingBottom: 110, gap: 20 }}>
    <View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }}><View><Eyebrow>Tuesday, May 15</Eyebrow><Text style={{ color: colors.text, fontSize: 30, fontWeight: '800', marginTop: 5 }}>Good morning, Alex</Text></View><View style={{ flexDirection: 'row', gap: 8 }}><IconButton icon="＋" onPress={() => router.push('/add')} /><IconButton icon={dark ? '☼' : '☾'} onPress={toggle} /></View></View>
    <Card style={{ backgroundColor: colors.accent, borderColor: colors.accent }}><View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }}><View><Text style={{ color: '#DADAFE', fontWeight: '700' }}>YOUR STREAK</Text><Text style={{ color: '#FFFFFF', fontSize: 42, fontWeight: '900' }}>7 days</Text><Text style={{ color: '#E8E8FF' }}>Keep the momentum going.</Text></View><Text style={{ fontSize: 50 }}>✦</Text></View></Card>
    <View style={{ flexDirection: 'row', gap: 12 }}><Card style={{ flex: 1 }}><Text style={{ color: colors.muted }}>Notes saved</Text><Text style={{ color: colors.text, fontSize: 27, fontWeight: '900' }}>{notes.length}</Text><Text style={{ color: colors.success, fontWeight: '700' }}>+2 this week</Text></Card><Card style={{ flex: 1 }}><Text style={{ color: colors.muted }}>Topics mastered</Text><Text style={{ color: colors.text, fontSize: 27, fontWeight: '900' }}>12</Text><Text style={{ color: colors.success, fontWeight: '700' }}>68% overall</Text></Card></View>
    <View style={{ flexDirection: 'row', gap: 12 }}><View style={{ flex: 1 }}><Button title="Ask a question" onPress={() => router.push('/ask')} /></View><View style={{ flex: 1 }}><Button title="Generate quiz" secondary onPress={() => router.push('/quiz')} /></View></View>
    <View style={{ gap: 10 }}><View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }}><Text style={{ color: colors.text, fontSize: 20, fontWeight: '800' }}>Coming up</Text><Link href="/deadlines" style={{ color: colors.accent, fontWeight: '700' }}>See all</Link></View>{deadlines.map((item) => <Card key={item.id} style={{ flexDirection: 'row', alignItems: 'center', paddingVertical: 14 }}><View style={{ width: 8, height: 40, borderRadius: 4, backgroundColor: item.urgency === 'this week' ? colors.danger : colors.warning }} /><View style={{ flex: 1 }}><Text style={{ color: colors.text, fontWeight: '800', fontSize: 16 }}>{item.title}</Text><Text style={{ color: colors.muted }}>{item.subject} · {item.date}</Text></View><Text style={{ color: item.urgency === 'this week' ? colors.danger : colors.warning, fontWeight: '800' }}>{item.days}d</Text></Card>)}</View>
    <View style={{ gap: 10 }}><Text style={{ color: colors.text, fontSize: 20, fontWeight: '800' }}>Focus next</Text><Card><Eyebrow>Weak topic</Eyebrow><Text style={{ color: colors.text, fontSize: 18, fontWeight: '800' }}>Electron transport chain</Text><Text style={{ color: colors.muted }}>You have seen this topic twice. A short quiz could help lock it in.</Text><Button title="Practice this topic" secondary onPress={() => router.push('/quiz')} /></Card></View>
  </ScrollView>;
}
